### ISSUE TITLE
ggbipca() gradient color scale

### ISSUE THREAD

**Issue by ukipo** [YoannPa/BiocompR#14]
Hi Yoann,

**Description**
I'm trying to color the points with a gradient color scale and not by groups.
Below, I used the mtcars data set to replicate my issue. After performing the PCA, I wanted to create a biplot with the points colored by weight on a gradient scale. Instead, the separate values are treated as individual groups and the colors do not represent the gradient.

I think it would be beneficial to add an option to color the points on a gradient scale.

**To replicate**
`mtcars.pca <- prcomp(mtcars[,c(1:5,7,10,11)], center = TRUE, scale. = TRUE)`
`ggbipca(prcomp.res = mtcars.pca, data = mtcars, color.data = "wt")`

Thank you!

**Comment by YoannPa** [comment]
Dear @ukipo ,
The latest version of BiocompR (0.0.171) adds your request to the supported features of ggbipca() and cross.biplot() functions.
Please re-install BiocompR with `devtools::install_github("YoannPa/BiocompR")`.
Best, 
Yoann.

**Comment by ukipo** [comment]
Hello @YoannPa ,
It works great, thank you! Modifying the gradient with `+ scale_colour_gradient()` and `+ scale_colour_gradient2()` works as well.
