### ISSUE TITLE
Is there any demonstration example document？

### ISSUE THREAD

**Issue by mumdark** [YoannPa/BiocompR#15]
Hi, thank you for developing such an excellent tool ! 

**Is there any example document that demonstrates how each function is used?**

Thanks!

**Comment by YoannPa** [comment]
Dear @mumdark ,
The package comes with a documentation. Most of the graphical functions (starting with the prefix **gg** for ggplot2) come with a documentation containing runnable examples.

After installing the package, you can access the documentation of a function within R like this, for example :
`?ggcraviola()` will open the documentation of the ggcraviola() function.
If you scroll down within the documentation you will find a section titled **Examples** with a clickable link **Run examples** right below.
Click it and the code provided to generate examples will execute itself (depending on the quantity of examples the execution of examples may take **few seconds, up to 3 minutes**).
This will produce a documentation where the code and the plots generated with it are both visible.

If runnable examples are missing for some of the functions you wish to use, just let me know which function it is, and I will produce examples for it.

I can also produce a folder with a bunch of examples as .png files and add them directly to the repository if you find it more convenient (you let me know).
I hope I answered your question.

Best regards, 

Yoann.

**Comment by mumdark** [comment]
Dear Yoann,

**Thanks**! 
The information you provided is quite helpful and sufficient for me.

Kind regards,
mumdark.
